# Data TRansformation
- convert the column which has wrong datatype to correct datatype
- convert text categorical into numeric
- convert the column, which has high magnitude to low magnitude

In [2]:
import pandas as pd

In [14]:
df = pd.DataFrame({"Age":[23,25,30,"32",40,50,31]})
df

  Age
0  23
1  25
2  30
3  32
4  40
5  50
6  31

In [15]:
df.dtypes

Age    object
dtype: object

In [16]:
df["Age"].unique()

array([23, 25, 30, '32', 40, 50, 31], dtype=object)

In [17]:
df["Age"] = df["Age"].astype(int)

# Encoding

- convert text categorical into numeric

In [35]:
df = pd.DataFrame({"Gender":["Male","Male","female", "Male", "female","XY","ij","ij"]})
df

   Gender
0    Male
1    Male
2  female
3    Male
4  female
5      XY
6      ij
7      ij

In [36]:
df["Gender"].unique()

array(['Male', 'female', 'XY', 'ij'], dtype=object)

In [37]:
df["Gender"] = df["Gender"].str.capitalize()

df["Gender"]

0      Male
1      Male
2    Female
3      Male
4    Female
5        Xy
6        Ij
7        Ij
Name: Gender, dtype: object

- Label Encoding == alphabetical encoding

In [38]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Gender"]  = le.fit_transform(df[["Gender"]])

df

C:\Users\SRK\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

   Gender
0       2
1       2
2       0
3       2
4       0
5       3
6       1
7       1